In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\bangalore house price prediction OHE-data.csv")
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.columns

Index(['bath', 'balcony', 'price', 'total_sqft_int', 'bhk', 'price_per_sqft',
       'area_typeSuper built-up  Area', 'area_typeBuilt-up  Area',
       'area_typePlot  Area', 'availability_Ready To Move',
       ...
       'location_Kalena Agrahara', 'location_Horamavu Agara',
       'location_Vidyaranyapura', 'location_BTM 2nd Stage',
       'location_Hebbal Kempapura', 'location_Hosur Road',
       'location_Horamavu Banaswadi', 'location_Domlur',
       'location_Mahadevpura', 'location_Tumkur Road'],
      dtype='object', length=108)

In [4]:
X= df.drop('price',axis=1)
y = df['price']
print(X.shape)
print(y.shape)

(7120, 107)
(7120,)

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state = 5)
print(X_train.shape)
print("/n 1",X_test)
print("/n 2 ",y_train)
print('/n 3',y_test)

(5696, 107)
/n 1       bath  balcony  total_sqft_int  bhk  price_per_sqft  \
4910   2.0      2.0          1360.0    3     4779.411765
6388   2.0      1.0          1150.0    2     4260.869565
1828   1.0      1.0           550.0    1     3090.909091
6675   2.0      1.0          1246.0    2     5216.693419
1468   2.0      3.0          1350.0    2    13333.333333
...    ...      ...             ...  ...             ...
629    2.0      1.0          1300.0    2     6076.923077
189    2.0      2.0          1460.0    3     6849.315068
4129   4.0      2.0          2408.0    3    10797.342193
6569   3.0      0.0          5720.0    3     6118.881119
6559   2.0      1.0           995.0    2     3499.497487

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
4910                              0                        1
6388                              0                        1
1828                              1                        0
6675                              1                        0
1468                              1                        0
...                             ...                      ...
629                               1                        0
189                               1                        0
4129                              1                        0
6569                              0                        1
6559                              1                        0

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
4910                    0                           1                    0
6388                    0                           1                    0
1828                    0                           1                    0
6675                    0                           1                    0
1468                    0                           1                    0
...                   ...                         ...                  ...
629                     0                           1                    0
189                     0                           1                    0
4129                    0                           1                    0
6569                    0                           1                    0
6559                    0                           1                    0

      ...  location_Kalena Agrahara  location_Horamavu Agara  \
4910  ...                         0                        0
6388  ...                         0                        0
1828  ...                         0                        0
6675  ...                         0                        0
1468  ...                         0                        0
...   ...                       ...                      ...
629   ...                         0                        0
189   ...                         0                        0
4129  ...                         0                        0
6569  ...                         0                        0
6559  ...                         0                        0

      location_Vidyaranyapura  location_BTM 2nd Stage  \
4910                        0                       0
6388                        0                       0
1828                        0                       0
6675                        0                       0
1468                        0                       0
...                       ...                     ...
629                         0                       0
189                         0                       0
4129                        0                       0
6569                        0                       0
6559                        0                       0

      location_Hebbal Kempapura  location_Hosur Road  \
4910                          0                    0
6388                          0                    0
1828                          0                    0
6675                          0                    0
1468                          0                    0
...                         ...                  ...
629                           0                    0
189                           0                    0
4129                          0                    0
6569                          0                    0
6559                          0                    0

      location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
4910                            0                0                     0
6388                            0                0                     0
1828                            0                0                     0
6675                            0                0                     0
1468                            0                0                     0
...                           ...              ...                   ...
629                             0                0                     0
189                             0                0                     0
4129                            0                0                     0
6569                            0                0                     0
6559                            0                0                     0

      location_Tumkur Road
4910                     0
6388                     0
1828                     0
6675                     0
1468                     0
...                    ...
629                      0
189                      0
4129                     0
6569                     0
6559                     0

[1424 rows x 107 columns]
/n 2  1214    120.00
5337     39.00
902      55.00
6288    135.00
2820     49.00
         ...
3046     46.90
1725     49.87
4079     32.00
2254     60.60
2915     45.00
Name: price, Length: 5696, dtype: float64
/n 3 4910     65.00
6388     49.00
1828     17.00
6675     65.00
1468    180.00
         ...
629      79.00
189     100.00
4129    260.00
6569    350.00
6559     34.82
Name: price, Length: 1424, dtype: float64

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train= sc.transform(X_train)
X_test = sc.transform(X_test)

# ML Model Training

In [7]:
from sklearn.linear_model import LinearRegression


lr= LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [8]:
lr.coef_

array([ 1.57948892e+00, -6.24440316e-01,  7.26309357e+01, -1.07301172e+01,
        6.29728985e+01,  5.09650617e-01, -1.11004908e+00, -4.61544115e+00,
       -2.04506459e+00, -3.43565912e+00, -2.40378094e+00,  4.42205485e-01,
       -1.11208490e+00,  1.78647722e+00,  1.49050266e-01, -1.53017700e+00,
       -4.40844371e-01,  2.27756833e+00, -1.58332676e+00,  2.42892168e+00,
       -2.74120753e+00, -1.72474224e+00, -9.59223388e-01, -8.66439475e-02,
        9.57636654e-01,  1.55637869e+00, -4.16047544e+00, -8.31474617e-01,
       -5.41381640e-01,  1.55886106e+00, -5.26589827e-01, -5.27813574e-01,
        6.59494253e-01, -1.55493799e+00, -2.27780462e-02, -1.23484937e+00,
        3.77517757e-01,  7.09928612e-01,  3.26283104e+00,  1.36263888e-01,
        4.50037731e-01,  1.81111365e-01, -3.83268122e-01,  1.05772055e+00,
       -1.69807753e+00, -2.48889358e+00,  1.59535677e-01,  5.84152069e-03,
       -6.91565734e-01, -3.88522708e-01, -9.84550403e-01,  3.08296431e-01,
        1.06924536e+00, -7.67545544e-01, -8.99016358e-01,  1.31609253e+00,
        2.05685115e+00, -2.89793493e-01, -2.00067251e+00, -1.11048267e+00,
        1.18195844e+00, -5.56686038e-01, -1.61992885e-01, -9.55471560e-02,
       -1.40938938e+00,  1.21009228e+00, -1.01741574e+00, -9.90595427e-01,
       -7.62877926e-01,  1.92616896e-01, -8.66374058e-01, -4.59502393e-01,
       -1.98113530e+00, -1.28402249e+00,  3.03465070e-01,  1.13819754e+00,
       -1.21810519e+00,  2.86351583e-01, -2.32733787e-01, -1.84377314e+00,
        4.84456683e-01, -8.28846279e-02,  5.48046833e-02,  3.11841976e+00,
        2.13347500e+00, -8.48576476e-01, -4.44043436e-01,  2.45989950e+00,
        2.74718394e-01,  3.13522955e-01,  1.60301553e-02,  1.45315201e+00,
        8.18225041e-01, -1.12800857e+00,  1.57914749e-01, -8.28931094e-01,
        1.25383273e+00,  7.72439751e-02,  1.01333494e+00,  5.86469101e-01,
       -4.04142151e-01, -1.46402576e+00, -7.45099397e-01,  6.84226979e-01,
       -1.83993413e+00,  2.78065195e-01, -6.91512321e-01])

In [9]:
lr.intercept_

95.81549596207864

In [10]:
X_test[0,:]

array([-0.44582073,  0.56284463, -0.13525641,  0.62477352, -0.44897581,
       -1.7151876 ,  2.09983493, -0.26051203,  0.50569944, -0.18474894,
       -0.15989734, -0.14979193, -0.13231119, -0.12953656, -0.12670528,
       -0.12010681, -0.12308052, -0.12308052, -0.116289  , -0.11551113,
       -0.10660036, -0.10909925, -0.10490288, -0.10575488, -0.09315135,
       -0.09218776, -0.08823182, -0.08618799, -0.09121434, -0.0830308 ,
       -0.08085949, -0.0830308 , -0.0830308 , -0.07862985, -0.08409599,
       -0.07276497, -0.07975227, -0.07276497, -0.07153563, -0.07153563,
       -0.07862985, -0.06901264, -0.07028523, -0.0739743 , -0.07975227,
       -0.06901264, -0.07028523, -0.0739743 , -0.07276497, -0.06504853,
       -0.06901264, -0.0677166 , -0.0677166 , -0.07028523, -0.07028523,
       -0.0677166 , -0.07028523, -0.06504853, -0.06504853, -0.06639573,
       -0.06504853, -0.06226825, -0.06367332, -0.07028523, -0.06083125,
       -0.06083125, -0.06367332, -0.06367332, -0.06367332, -0.06226825,
       -0.06083125, -0.06083125, -0.0677166 , -0.06083125, -0.06083125,
       -0.05935999, -0.05471275, -0.06083125, -0.05935999, -0.05785186,
       -0.06226825, -0.05307449, -0.06226825, -0.06226825, -0.05307449,
       -0.06083125, -0.05785186, -0.06083125, -0.06083125, -0.06367332,
       -0.05630391, -0.05630391, -0.05471275, -0.06083125, -0.05785186,
       -0.05785186, -0.05138463, -0.04594768, -0.05471275, -0.05471275,
       -0.05471275, -0.05471275, -0.05785186, -0.05138463, -0.05307449,
       -0.05138463, -0.05630391])

In [11]:
lr.predict([X_test[0,:]])

array([48.76196303])

In [12]:
lr.predict(X_test)

array([ 48.76196303,  50.40769844,  -8.70142108, ..., 294.07772346,
       453.49139083,   3.68867426])

In [13]:
y_test

4910     65.00
6388     49.00
1828     17.00
6675     65.00
1468    180.00
         ...
629      79.00
189     100.00
4129    260.00
6569    350.00
6559     34.82
Name: price, Length: 1424, dtype: float64

In [14]:
print(lr.score(X_test,y_test)*100,"%")

86.55250786506055 %