In [6]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\akashDATACancer.csv")
# C:\Users\AKASH SONI\Desktop\FILES

# data['Class']=data.dropna(subset=['Class'])
data1= data.replace("NaN",np.nan)
data2= data1.fillna(0)
#  data2['Class'] = data2.dropna(subset=['Class'])
# data['Class'].isnull().sum()
# data2.isnull().sum()
# data2[['Class']]
data

,Idx,SampleID,SampleType,Class,M1,M2,M3,M4,M5,M6,...,M140,M141,M142,M143,M144,M145,M146,M147,M148,M149
0,1,sample_1,QC,QC,90.1,491.6,202.9,35.0,164.2,19.7,...,115.1,64.8,25.5,473.9,26.5,NaN,6.8,118.6,710.6,203.6
1,2,sample_2,Sample,GC,43.0,525.7,130.2,NaN,694.5,114.5,...,84.2,357.1,16.1,455.5,29.5,28.1,35.8,316.1,390.7,199.0
2,3,sample_3,Sample,BN,214.3,10703.2,104.7,46.8,483.4,152.3,...,993.5,1698.5,32.9,75.9,33.2,802.8,967.6,154.4,31.6,195.2
3,4,sample_4,Sample,HE,31.6,59.7,86.4,14.0,88.6,10.3,...,58.1,83.5,60.5,136.9,17.0,10.2,24.7,64.1,91.4,91.6
4,5,sample_5,Sample,GC,81.9,258.7,315.1,8.7,243.2,18.4,...,44.5,47.6,45.6,1441.7,35.2,0.1,22.8,135.0,322.3,254.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,136,sample_136,QC,QC,97.6,341.1,232.1,38.1,174.0,7.7,...,79.7,101.8,23.9,296.0,25.0,NaN,7.5,141.5,675.7,200.8
136,137,sample_137,Sample,GC,405.3,510.7,521.9,91.9,732.1,145.7,...,434.8,84.8,182.3,110.7,123.9,0.4,36.3,60.1,317.3,401.7
137,138,sample_138,Sample,BN,45.4,191.6,41.0,18.7,40.8,32.2,...,45.3,44.5,14.5,83.8,27.9,0.3,0.5,47.3,47.8,46.5
138,139,sample_139,Sample,HE,30.7,56.8,35.9,20.9,17.4,NaN,...,28.0,38.7,1.3,130.9,24.6,0.7,5.9,20.7,124.1,28.9
139,140,sample_140,QC,QC,99.8,342.7,247.4,28.0,166.6,11.1,...,148.2,97.7,22.9,439.7,24.7,NaN,6.4,129.4,670.1,202.5

In [48]:
def healthFunc(k):
    if k == "QC":
        return 0
    if k == "GC":
        return 1
    if k == "BN":
        return 2 
    if k == "HE":
        return 3

    
data2[['Class']]=data2['Class'].apply(healthFunc)
x=data2.iloc[:,4:].values
y=data2[['Class']]

# for i in enumerate(y):
#     y[i]=y.astype('int')
# # y=y.astype('int').values
# y

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y)

print(x_train.size)
print(y_train.size)

print(x_test.size)
print(y_test.size)

15645
105
5215
35

In [49]:
from sklearn import tree
t= tree.DecisionTreeClassifier()
t.fit(x_train,y_train)

DecisionTreeClassifier()

In [51]:
t.predict(x_test)

array([1, 1, 3, 2, 2, 2, 1, 2, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 0, 1,
       0, 0, 0, 2, 0, 3, 3, 3, 2, 3, 1, 2, 0], dtype=int64)