In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\datasets\\final_data.csv")
data.head()

,sample_id,sample_id_study,CLIENT_IDENTIFIER,CLIENT_MATRIX,DAY,Health,Time,HEALTH_STATUS,RUN_DAY,SAMPLE_AMT,SUBJECT,Time Point,study_group,sex,BMI,hba1c
0,sample_0001,2904988,101-d2-MMT(-0.5h)-S002,Serum,D2,Healthy,Pre,healthy subjects,1,200 ul,101,pre,Healthy_D2_Pre,f,27.9,5.05
1,sample_0002,2904989,101-d2-MMT(+1h)-S032,Serum,D2,Healthy,Post,healthy subjects,1,200 ul,101,1h,Healthy_D2_Post,f,27.9,5.05
2,sample_0003,2904991,101-d14-MMT(-0.5h)-S002,Serum,D14,Healthy,Pre,healthy subjects,1,200 ul,101,pre,Healthy_D14_Pre,f,27.9,5.05
3,sample_0004,2904992,101-d14-MMT(+1h)-S032,Serum,D14,Healthy,Post,healthy subjects,1,200 ul,101,1h,Healthy_D14_Post,f,27.9,5.05
4,sample_0005,2904994,101-d28-MMT(-0.5h)-S002,Serum,D28,Healthy,Pre,healthy subjects,1,200 ul,101,pre,Healthy_D28_Pre,f,27.9,5.05

In [3]:
data.columns

Index(['sample_id', 'sample_id_study', 'CLIENT_IDENTIFIER', 'CLIENT_MATRIX',
       'DAY', 'Health', 'Time', 'HEALTH_STATUS', 'RUN_DAY', 'SAMPLE_AMT',
       'SUBJECT', 'Time Point', 'study_group', 'sex', 'BMI', 'hba1c'],
      dtype='object')

In [4]:
del data['sample_id']
del data['sample_id_study']
del data['CLIENT_IDENTIFIER']
del data['CLIENT_MATRIX']
del data['Time Point']
del data['study_group']
del data['Time']

In [5]:
data.head()

,DAY,Health,HEALTH_STATUS,RUN_DAY,SAMPLE_AMT,SUBJECT,sex,BMI,hba1c
0,D2,Healthy,healthy subjects,1,200 ul,101,f,27.9,5.05
1,D2,Healthy,healthy subjects,1,200 ul,101,f,27.9,5.05
2,D14,Healthy,healthy subjects,1,200 ul,101,f,27.9,5.05
3,D14,Healthy,healthy subjects,1,200 ul,101,f,27.9,5.05
4,D28,Healthy,healthy subjects,1,200 ul,101,f,27.9,5.05

In [6]:


data['DAY'] = data['DAY'].str.replace("D","").astype(int)






def healthFunc(k):
    if k == "Healthy":
        return 0
    if k == "prediabetic":
        return 1
    if k == "diabetic":
        return 2 

    
data['Health']=data['Health'].apply(healthFunc)


def HealthQues(k):
    if k == 0:
        return "Healthy"
    if k == 1:
        return "prediabetic"
    if k == 2:
        return "diabetic"

In [7]:
def healthStatusFunc(k):
    if k == 'healthy subjects':
        return 0
    if k == 'prediabetic':
        return 1
    if k == 'diabetic subjects':
        return 2 

    
data['HEALTH_STATUS']=data['HEALTH_STATUS'].apply(healthStatusFunc)


def HealthStatus(k):
    if k == 0:
        return "healthy subjects"
    if k == 1:
        return "prediabetic"
    if k == 2:
        return "diabetic subjects"
    



# data = pd.concat([data, gender],axis=1)
# data.head()

# data['Health']

In [8]:
data['SAMPLE_AMT'] = data['SAMPLE_AMT'].str.replace(" ul","").astype(int)

In [9]:
gender = pd.get_dummies(data["sex"])

In [10]:


data = pd.concat([data, gender],axis=1)
# data.drop('sex',axis=1)
del data['sex']
data.head()

   DAY  Health  HEALTH_STATUS  RUN_DAY  SAMPLE_AMT  SUBJECT   BMI  hba1c  f  m
0    2       0              0        1         200      101  27.9   5.05  1  0
1    2       0              0        1         200      101  27.9   5.05  1  0
2   14       0              0        1         200      101  27.9   5.05  1  0
3   14       0              0        1         200      101  27.9   5.05  1  0
4   28       0              0        1         200      101  27.9   5.05  1  0

In [11]:
x1 = data.iloc[:,0:2]
x2 = data.iloc[:,3:10]
x=pd.concat([x1,x2],axis=1).values

y = data['HEALTH_STATUS'].values
x

array([[ 2.  ,  0.  ,  1.  , ...,  5.05,  1.  ,  0.  ],
       [ 2.  ,  0.  ,  1.  , ...,  5.05,  1.  ,  0.  ],
       [14.  ,  0.  ,  1.  , ...,  5.05,  1.  ,  0.  ],
       ...,
       [14.  ,  2.  ,  3.  , ...,  9.1 ,  0.  ,  1.  ],
       [28.  ,  2.  ,  3.  , ...,  9.1 ,  0.  ,  1.  ],
       [28.  ,  2.  ,  3.  , ...,  9.1 ,  0.  ,  1.  ]])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y)

In [13]:
from sklearn import tree

t= tree.DecisionTreeClassifier()

t.fit(x_train,y_train)

DecisionTreeClassifier()

In [14]:
pr=t.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pr)*100,'%')

100.0 %