In [1]:
import pandas as pd

# How to write CSV in Pandas

In [2]:
pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv")

,TruFal,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
0,Yes,Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,...,436.0,22.0,9.0,481.0,691.0,1.0,10718.0,88.0,69.0,8.0
2,Yes,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,...,2.0,2.0,0.0,4.0,0.0,1.0,5.0,1.0,1.0,4.8
3,Yes,The Big Parade,1925.0,Drama|Romance|War,NaN,USA,Not Rated,151.0,1.33,245000.0,...,81.0,12.0,6.0,108.0,226.0,0.0,4849.0,45.0,48.0,8.3
4,Yes,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,...,136.0,23.0,18.0,203.0,12000.0,1.0,111841.0,413.0,260.0,8.3
5,Yes,Pandora’s Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,...,426.0,20.0,3.0,455.0,926.0,1.0,7431.0,84.0,71.0,8.0

In [3]:
type(pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv"))

pandas.core.frame.DataFrame

In [4]:
pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",nrows=3)

,TruFal,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
0,Yes,Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,...,436.0,22.0,9.0,481.0,691.0,1.0,10718.0,88.0,69.0,8.0
2,Yes,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,...,2.0,2.0,0.0,4.0,0.0,1.0,5.0,1.0,1.0,4.8

In [5]:
d =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv")
d.columns

Index(['TruFal', 'Year', 'Genres', 'Language', 'Country', 'Content Rating',
       'Duration', 'Aspect Ratio', 'Budget', 'Gross Earnings', 'Director', '…',
       'Facebook Likes – Actor 1', 'Facebook Likes – Actor 2',
       'Facebook Likes – Actor 3', 'Facebook Likes – cast Total',
       'Facebook likes – Movie', 'Facenumber in posters', 'User Votes',
       'Reviews by Users', 'Reviews by Crtiics', 'IMDB Score', 'Unnamed: 22'],
      dtype='object')

In [6]:
d1 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",usecols=[1,4,7])
d1

                                               Year Country  Aspect Ratio
0                                             Title     NaN           NaN
1  Intolerance: Love’s Struggle Throughout the Ages     NaN         123.0
2                    Over the Hill to the Poorhouse     NaN         110.0
3                                    The Big Parade     NaN         151.0
4                                        Metropolis  German         145.0
5                                     Pandora’s Box  German         110.0

In [7]:
d2 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",skiprows=[1,2,3,4])
d2

,TruFal,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
0,Yes,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,...,136,23,18,203,12000,1,111841,413,260,8.3
1,Yes,Pandora’s Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,...,426,20,3,455,926,1,7431,84,71,8.0

In [8]:
d =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv", index_col='Language')
d

,TruFal,Year,Genres,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,Director,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
Language,,,,,,,,,,,,,,,,,,,,,
NaN,Yes,Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Drama|History|War,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916.0,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481.0,691.0,1.0,10718.0,88.0,69.0,8.0
Crime|Drama,Yes,Over the Hill to the Poorhouse,1920.0,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4.0,0.0,1.0,5.0,1.0,1.0,4.8
Drama|Romance|War,Yes,The Big Parade,1925.0,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108.0,226.0,0.0,4849.0,45.0,48.0,8.3
Drama|Sci-Fi,Yes,Metropolis,1927.0,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203.0,12000.0,1.0,111841.0,413.0,260.0,8.3
Crime|Drama|Romance,Yes,Pandora’s Box,1929.0,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455.0,926.0,1.0,7431.0,84.0,71.0,8.0

In [9]:
d3 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",header=1)
d3

,Yes,Title,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,...,436,22,9,481,691,1,10718,88,69,8.0
1,Yes,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,...,2,2,0,4,0,1,5,1,1,4.8
2,Yes,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,...,81,12,6,108,226,0,4849,45,48,8.3
3,Yes,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,...,136,23,18,203,12000,1,111841,413,260,8.3
4,Yes,Pandora’s Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,...,426,20,3,455,926,1,7431,84,71,8.0

In [10]:
d4 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",header = None,prefix="Col")
d4

,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,...,Col13,Col14,Col15,Col16,Col17,Col18,Col19,Col20,Col21,Col22
0,TruFal,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,NaN
1,Yes,Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907,...,436,22,9,481,691,1,10718,88,69,8.0
3,Yes,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000,...,2,2,0,4,0,1,5,1,1,4.8
4,Yes,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000,...,81,12,6,108,226,0,4849,45,48,8.3
5,Yes,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000,...,136,23,18,203,12000,1,111841,413,260,8.3
6,Yes,Pandora’s Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,...,426,20,3,455,926,1,7431,84,71,8.0

In [11]:
d5 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\FILES\\frgi.csv",names=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p'])
d5

                                                                                                                                a  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Aspect Ratio
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                 NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated           123
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                 110
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated           151
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated           145
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated           110

                                                                                                                          b  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Budget
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN           NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated    1.33
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN          1.33
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated    1.33
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated    1.33
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated    1.33

                                                                                                                                  c  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Gross Earnings
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                   NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated          385907
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                100000
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated          245000
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated         6000000
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated             NaN

                                                                                                                            d  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Director
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN             NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated       NaN
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN         3000000
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated       NaN
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated     26435
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated      9950

                                                                                                                                       e  \
TruFal Year                                             Genres Language            Country Content Rating Duration                     …
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                        NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated        D.W. Griffith
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN          Harry F. Millarde
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated           King Vidor
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated           Fritz Lang
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated  Georg Wilhelm Pabst

                                                                                                                                            f  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facebook Likes – Actor 1
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                             NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                         …
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                               …
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                         …
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                         …
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                         …

                                                                                                                                            g  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facebook Likes – Actor 2
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                             NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                       436
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                               2
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                        81
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                       136
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                       426

                                                                                                                                            h  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facebook Likes – Actor 3
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                             NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                        22
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                               2
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                        12
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                        23
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                        20

                                                                                                                                               i  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facebook Likes – cast Total
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                                NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                            9
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                                  0
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                            6
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                           18
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                            3

                                                                                                                                          j  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facebook likes – Movie
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                           NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                     481
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                             4
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                     108
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                     203
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                     455

                                                                                                                                         k  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Facenumber in posters
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                          NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                    691
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                            0
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                    226
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                  12000
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                    926

                                                                                                                              l  \
TruFal Year                                             Genres Language            Country Content Rating Duration   User Votes
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN               NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated           1
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                 1
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated           0
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated           1
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated           1

                                                                                                                                    m  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Reviews by Users
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                     NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated             10718
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                       5
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated              4849
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated            111841
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated              7431

                                                                                                                                      n  \
TruFal Year                                             Genres Language            Country Content Rating Duration   Reviews by Crtiics
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN                       NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated                  88
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                         1
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated                  45
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated                 413
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated                  84

                                                                                                                              o  \
TruFal Year                                             Genres Language            Country Content Rating Duration   IMDB Score
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN               NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated          69
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN                 1
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated          48
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated         260
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated          71

                                                                                                                       p
TruFal Year                                             Genres Language            Country Content Rating Duration   NaN
Yes    Title                                            NaN    NaN                 NaN     NaN            NaN        NaN
       Intolerance: Love’s Struggle Throughout the Ages 1916   Drama|History|War   NaN     USA            Not Rated  8.0
       Over the Hill to the Poorhouse                   1920   Crime|Drama         NaN     USA            NaN        4.8
       The Big Parade                                   1925   Drama|Romance|War   NaN     USA            Not Rated  8.3
       Metropolis                                       1927   Drama|Sci-Fi        German  Germany        Not Rated  8.3
       Pandora’s Box                                    1929   Crime|Drama|Romance German  Germany        Not Rated  8.0

In [12]:
d.head()

,TruFal,Year,Genres,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,Director,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
Language,,,,,,,,,,,,,,,,,,,,,
NaN,Yes,Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Drama|History|War,Yes,Intolerance: Love’s Struggle Throughout the Ages,1916.0,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481.0,691.0,1.0,10718.0,88.0,69.0,8.0
Crime|Drama,Yes,Over the Hill to the Poorhouse,1920.0,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4.0,0.0,1.0,5.0,1.0,1.0,4.8
Drama|Romance|War,Yes,The Big Parade,1925.0,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108.0,226.0,0.0,4849.0,45.0,48.0,8.3
Drama|Sci-Fi,Yes,Metropolis,1927.0,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203.0,12000.0,1.0,111841.0,413.0,260.0,8.3

In [13]:
d.tail(2)

,TruFal,Year,Genres,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,Director,...,Facebook Likes – Actor 2,Facebook Likes – Actor 3,Facebook Likes – cast Total,Facebook likes – Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 22
Language,,,,,,,,,,,,,,,,,,,,,
Drama|Sci-Fi,Yes,Metropolis,1927.0,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203.0,12000.0,1.0,111841.0,413.0,260.0,8.3
Crime|Drama|Romance,Yes,Pandora’s Box,1929.0,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455.0,926.0,1.0,7431.0,84.0,71.0,8.0

In [14]:
d6 =pd.read_csv("C:\\Users\\AKASH SONI\\Desktop\\frgi.csv",dtype={'Budget':'int'})

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AKASH SONI\\Desktop\\frgi.csv'